version: "3.7"

services: 
    plangenerator:
        image: invaa/plangenerator:latest
        hostname: plangenerator
        expose:
            - "8080"

    ngnix-server:
        image: nginx:1.13
        ports: 
            - "8080:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - plangenerator

networks: 
    default:
        driver: bridge
        name: plangenerator_network
